### ISSUE TITLE
Cn document version management

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/document-cn-translation-of-skywalking#17]
Should we place all current document to 6.1? And we copy and update to each version folder. 

Do we you better suggestion?

**Comment by kezhenxu94** [comment]
> Should we place all current document to 6.1? And we copy and update to each version folder.

Since all the current documentation are based on master branch of the main repo, which includes parts of 6.1, and the 6.1 version is about to released, I think it's fine to put what we have now into 6.1.

And I noticed that the docs in main repo changed, should we create a new issue here to track them?

**Comment by wu-sheng** [comment]
Yes. I agree.

**Comment by wu-sheng** [comment]
Begin to set issues for this.
