### ISSUE TITLE
SkyWalking 6.2 document update

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/document-cn-translation-of-skywalking#23]
Set this document to link PRs in the main repo.

**Comment by SataQiu** [comment]
@wu-sheng 
Does the SkyWalking 6.2 document need to be translated based on the master branch?
I also want to try my hand at documentation.

**Comment by JaredTan95** [comment]
> @wu-sheng
> Does the SkyWalking 6.2 document need to be translated based on the master branch?
> I also want to try my hand at documentation.

Just do It! :P

**Comment by wu-sheng** [comment]
Yes. I hope this project could connect the translation group together, and keep the document update. We create an issue for each version of SkyWalking, to track the document changes.

@kezhenxu94 leads the document project here.

**Comment by kezhenxu94** [comment]
Hi @SataQiu , welcome and thank you for your interest in our work.

> Does the SkyWalking 6.2 document need to be translated based on the master branch?

Probably YES, because we haven't found a perfect way to hold multi-version documentations (such as based on tags or branches), what we'll do is put the docs of each version into a seperated folder. I'll create another folder for version 6.2 soon

**Comment by kezhenxu94** [comment]
Hi @wu-sheng , to create a new folder to hold the docs of 6.2.0, I think there are two ways:

- create the new folder on master branch: since the docs on master would be deployed to GitHub pages and the 6.2.0 is not released yet, it would be confusing to users who are reading the docs.

- create the new folder on a new branch (say 6.2.0), and merge it after 6.2.0 officially released: won't be deployed to GitHub pages, but contributors may be not aware that they should open pull requests against this branch, this may not be a big problem since we can change the default branch to 6.2.0, and we can change the base branch of a PR too.
  
I personally perfer the second way, what's your suggestion.

Kindly Regards

**Comment by wu-sheng** [comment]
I suggest you create a folder named `master` or `dev`, keep tracking the change there, when release happens, rename to new version number, then recreate a new `master` or `dev` folder.
